### ISSUE TITLE
Clone of existing volume fails

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#2065] opened 2018-02-06 20:02 UTC
Clone of an existing volume fails with error - ```Error response from daemon: create CloneVolume: VolumeDriver.Create: Server returned an error: TypeError("'NoneType' object does not support item assignment",)```

Steps:
1. Create a volume
```
root@promc-2n-dhcp105-23:~# docker volume create -d vsphere --name MyVolume
MyVolume
root@promc-2n-dhcp105-23:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      MyVolume@Datastore1
vfile:latest        vfilevolume488530
```
2. Clone a volume to create a new volume
``` 
root@promc-2n-dhcp105-23:~# docker volume create --driver=vsphere --name=CloneVolume -o clone-from=MyVolume -o access=read-only
Error response from daemon: create CloneVolume: VolumeDriver.Create: Server returned an error: TypeError("'NoneType' object does not support item assignment",)
root@promc-2n-dhcp105-23:~#

```

vmdk_ops.log

```
02/06/18 19:22:55 1703101 [Ubuntu.16.04.vsan-Datastore1._DEFAULT.CloneVolume] [INFO   ] *** cloneVMDK: /vmfs/volumes/Datastore1/dockvols/11111111-1111-1111-1111-111111111111/CloneVolume.vmdk opts = {'acc
02/06/18 19:22:55 1703101 [Ubuntu.16.04.vsan-Datastore1._DEFAULT.CloneVolume] [WARNING] Internal: Tenant name symlink not found for path /vmfs/volumes/Datastore1/dockvols/_DEFAULT
02/06/18 19:22:55 1703101 [Ubuntu.16.04.vsan-Datastore1._DEFAULT.CloneVolume] [ERROR  ] Failed to access b'/vmfs/volumes/Datastore1/dockvols/11111111-1111-1111-1111-111111111111/CloneVolume-a84079d57d3e3
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/Python/kvESX.py", line 297, in load
    with open(meta_file, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: b'/vmfs/volumes/Datastore1/dockvols/11111111-1111-1111-1111-111111111111/CloneVolume-a84079d57d3e3be3.vmfd'
02/06/18 19:22:55 1703101 [Ubuntu.16.04.vsan-Datastore1._DEFAULT.CloneVolume] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1843, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1148, in executeRequest
    vm_datastore=vm_datastore)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 208, in createVMDK
    vm_datastore=vm_datastore)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 394, in cloneVMDK
    vol_meta[kv.CREATED_BY] = vm_name
TypeError: 'NoneType' object does not support item assignment
```

vmdk_ops.log: 
[vmdk_ops.txt](https://github.com/vmware/vsphere-storage-for-docker/files/1700618/vmdk_ops.txt)

**Comment by govint** [comment] 2018-02-07 12:27
The earliest logs in vmdk_ops starts at 02/05/18 20:56:37 and doesn't have the exception in it. If its repro'able can we get a new repro and get those logs?

KV seems to have error'ed getting the volume KV data and hence the none-type error.

**Comment by ashahi1** [comment] 2018-02-08 04:05
@govint I have updated the new logs. Can you please take a look at it again?

Volume name: testvolume@Datastore1
Cloned volume: TestCloneVolume

Docker cli:
```
root@promc-2n-dhcp105-23:~# docker volume create -d vsphere --name testvol2
testvol2
root@promc-2n-dhcp105-23:~#
root@promc-2n-dhcp105-23:~# docker volume create -d vsphere --name testvolume
testvolume
root@promc-2n-dhcp105-23:~#
root@promc-2n-dhcp105-23:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      testvolume@Datastore1
root@promc-2n-dhcp105-23:~#
root@promc-2n-dhcp105-23:~# docker volume create --driver=vsphere --name=TestCloneVolume -o clone-from=testvolume -o access=read-only
Error response from daemon: create TestCloneVolume: VolumeDriver.Create: Server returned an error: TypeError("'NoneType' object does not support item assignment",)
root@promc-2n-dhcp105-23:~#
```

Admin cli:
```
[root@sc2-rdops-vm09-dhcp-35-191:~] esxcli storage guestvol volume ls
Volume           Datastore   VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By         Created Date
---------------  ----------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  -----------------  ------------------------
testvolume       Datastore1  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Ubuntu.16.04.vsan  Thu Feb  8 03:40:50 2018
TestCloneVolume  Datastore1  _DEFAULT  100MB     13MB  N/A         N/A     N/A          detached     read-write  independent_persistent  N/A                N/A
[root@sc2-rdops-vm09-dhcp-35-191:~]
```

Logs:
[vmdk_ops.log](https://github.com/vmware/vsphere-storage-for-docker/files/1705680/vmdk_ops.log)
[vsphere-storage-for-docker.log](https://github.com/vmware/vsphere-storage-for-docker/files/1705681/vsphere-storage-for-docker.log)

**Comment by govint** [comment] 2018-02-08 12:44
@ashahi1, sorry the vmdk_ops.log is now really outdated, the last log is from 11/29/17 22:05:47. Can you upload the one that has the errors in it.

So the volume is getting created ok but the KV file is somehow not accessible.

**Comment by govint** [comment] 2018-03-08 10:38
@carcampbell, please open a separate issue and post the ESX host side logs (/var/log/vmware/vmdk_ops.log) and the Linux side logs for the volume plugin.  The issue posted earlier by @ashahi1  is related to a regression that has since been fixed (see , https://github.com/vmware/vsphere-storage-for-docker/releases/tag/0.21.1).

I'll be closing this issue and you can make a new one that we can debug. Please also include the version of the plugin and VIB you are using.

**Comment by govint** [comment] 2018-03-10 08:50
Closing per earlier comment. Please open a new issue and provide the logs in that and the details listed in my earlier comment.

**Closed by govint** 2018-03-10 08:50 UTC
Labels: P0, component/test-infrastructure
