### ISSUE TITLE
Volume access update from admin cli fails with short volume name.

### ISSUE THREAD

**Issue by pshahzeb** [vmware/vsphere-storage-for-docker#1304] opened 2017-05-26 23:15 UTC
If short volume name is used to update volume access through admin cli, the update fails.
But works for with full volume name.
Since access update requires specifying vmgroup, the short name should be fine for access update.

The reason why it fails is because set_vol_opts  only relies on volume name supplied in arguement.
If datastore isn't present,  it fails.
This function should retrieve the default datastore for the vmgroup in such cases.

Admin cli:
```
[root@sc2-rdops-vm01-dhcp-59-225:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume                        Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By    Created Date
----------------------------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ------------  ------------------------
test1                         sharedVmfs-0  _DEFAULT  100MB     16MB  ext4        N/A     thin         detached     read-write  independent_persistent  ubuntu-VM0.2  Thu May 25 23:21:36 2017


[root@sc2-rdops-vm01-dhcp-59-225:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume set --vmgroup _DEFAULT --volume=test1 --options="access=read-only"
Failed to update access=read-only for test1.

[root@sc2-rdops-vm01-dhcp-59-225:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume set --vmgroup _DEFAULT --volume=test1@sharedVmfs-0 --options="access=read-only"
Successfully updated settings for : test1@sharedVmfs-0
```

**Comment by govint** [comment] 2017-09-13 06:47
Setting to spiderman, the code isn't broken but needs to be enhanced when DS name isn't specified.

**Comment by shaominchen** [comment] 2017-09-28 21:19
Seems a non-critical correctness issue - mark as mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment] 2017-10-13 23:56
> If short volume name is used to update volume access through admin cli, the update fails.

First of all this is *not* a bug, it is by design to pass full volume name (dropping the `king/bug` kw). See below for the reference, it is failing as per the expectation; we can improve the error message if the current implementation fails to do so.

```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol volume set

Usage: esxcli storage guestvol volume set [cmd options]

Description: 
  set                   Edit settings for a given volume

Cmd options:
  --options=<str>       Options (specifically, access) to be set on the volume (required)
  --vmgroup=<str>       Name of the vmgroup the volume belongs to (required)
  --volume=<str>        Volume to set options for, specified as "volume@datastore" (required)
```

> This function should retrieve the default datastore for the vmgroup in such cases.

Now let's consider a case for improving this further as per above suggestion. IMO it will become complex unnecessary and it will not work *always* and user, in this case an admin, has to pass full name in case of one of the following situation after volume creation.

1. When the vmgroup's default datastore changes 
2. SVMotion of VM to a different datastore after volume creation (when vmgroup's default datastore is `_VM_DS`)

@govint I am proposing not to go forward with improvement and keep the implementation as is and close this issue.. Please share your thoughts.

**Comment by govint** [comment] 2017-10-15 04:07
Frankly, user having to specify datastore is something that we shouldn't carry forward for vDVS. Users can't be expected to know what datastores exist on a host and then on each host either. If user can provide either format (short and long names) in other ESXCLI commands then it needs to be supported here also. 

But its not a must-fix now and can be deferred till we decide what format volume names can be specified with uniformly in all commands.

**Comment by shuklanirdesh82** [comment] 2017-10-15 05:36
> But its not a must-fix now and can be deferred till we decide what format volume names can be specified with uniformly in all commands.

Sure, removing `mustfix` kw.

> Frankly, user having to specify datastore is something that we shouldn't carry forward for vDVS. Users can't be expected to know what datastores exist on a host and then on each host either.

In this scenario (`admin_cli volume set`) user is an Admin which is OK to know of datastore I guess.

**Closed** 2018-01-03 04:34 UTC
Labels: kind/usability, P1, wontfix
