### ISSUE TITLE
docker daemon failed to start after installing vDVS plugin

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#2035] opened 2017-12-11 19:03 UTC
This issue was reported on the slack channel for docker-volume-vsphere. Posting the details from the information posted by the customer on the slack channel.

Issue as reported by customer:

"Just tried hatchway for the first time.  After running the following command the docker daemon bombed out and will no longer restart even after rebooting the vm:"
```
docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:0.19`
```

Journalctl logs:
```Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/15fdae39e1
97a5348936b980a825af7795bb7494b72fe9e4df6dec3d458a328c/config.json: open /var/lib/docker/plugins/15fdae39e197a5348936b980a825af7795bb7494b72fe9e4df6dec3d458a328c/config.json
: no such file or directory
Dec 10 22:38:06 docker-client systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 22:38:06 docker-client systemd[1]: Failed to start Docker Daemon.
Dec 10 22:38:06 docker-client systemd[1]: docker.service: Unit entered failed state.
Dec 10 22:38:06 docker-client systemd[1]: docker.service: Failed with result 'exit-code'.```

**Comment by ashahi1** [comment] 2017-12-11 19:03
@shuklanirdesh82 can you please take a look?

**Comment by james65535** [comment] 2017-12-11 23:15
Feel free to reach out to me if any further info is required, I will keep the affected docker host around in case the issue is not easily replicated.

**Comment by govint** [comment] 2017-12-12 04:11
@james65535 can you upload the plugin logs if any (/var/log/docker-volume-vsphere.log). SHouldn't this issue be raised on Moby, if the docker daemon is down.

# docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:0.19
0.19: Pulling from vmware/docker-volume-vsphere
9bb07d39b032: Download complete
Digest: sha256:278cf4ffc37d5dacddab470d1fe4a55a3d93c3368b8f2ff8f6a0675ff49f8179
Status: Downloaded newer image for vmware/docker-volume-vsphere:0.19
Installed plugin vmware/docker-volume-vsphere:0.19


This is what I got with,
# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by james65535** [comment] 2017-12-12 04:54
Thanks for the follow up, `/var/log/docker-volume-vsphere.log` doesn't exist. Also, I cannot do a `docker version` as the server is offline.  I note your comment about Moby, I'm fine with closing this issue if its not helpful for the project; my initial intent was to just discuss it in slack.

**Comment by shuklanirdesh82** [comment] 2017-12-12 05:33
> Also, I cannot do a docker version as the server is offline.

@james65535 It seems docker is not configured properly. Can you configure and give a shot again?

Closing this issue, let's reopen if the issue persists even after configure docker correctly.

**Comment by shuklanirdesh82** [comment] 2017-12-12 05:54
@ashahi1 can you please perform plugin installation on the photon 1.0 VM with docker 1.13.1?

Here is the detail that I know of:

docker: 1.13.1
OS: Photon 1.0 (4.4.62-1.ph1-esx)
```
uname -a `Linux docker-client 4.4.62-1.ph1-esx #1-photon SMP Wed Apr 26 23:41:32 UTC 2017 x86_64 GNU/Linux`
```

**Closed** 2017-12-21 02:06 UTC
Labels: customer, kind/bug, P0
